"""Upgrade User

Revision ID: 4bb81edde21a
Revises: ed1d7ecdd055
Create Date: 2024-12-16 21:57:16.209283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bb81edde21a'
down_revision: Union[str, None] = 'ed1d7ecdd055'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'repeat_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('repeat_password', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
