"""Upgrade User

Revision ID: ed1d7ecdd055
Revises: 7e2dc75e393d
Create Date: 2024-12-16 21:32:14.034785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed1d7ecdd055'
down_revision: Union[str, None] = '7e2dc75e393d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('repeat_password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'repeat_password')
    # ### end Alembic commands ###
